#!/bin/bash

# THOUGHTS
# -vcodec and -f image2pipe are the correct tools to use here
# the goal is to be able to take input until the frame is done,
# and then use waifu2x to process that frame, and stream that to
# another ffmpeg instance to add it to a video

# https://batchloaf.wordpress.com/2017/02/12/a-simple-way-to-read-and-write-audio-and-video-files-in-c-using-ffmpeg-part-2-video/
# this guy does exactly what i'm trying (without the waifu)
# he uses -vcodec rawvideo -pix_fmt rgb24 to get raw output
# i'll need to check if waifu2x can take raw input
# graphicsmagick can, but reqiures extra command line info
# so probably just use png for now

ffmpeg -i $1 -ss 00:00:01.000 -vframes $3 -vcodec bmp -f image2pipe - > $2